export const projectsData = [
  {
    id: 2,
    title:
      "Spatial Analysis of Tuberculosis Prevalence in Nepal from 2019 to 2023",
    description:
      'Axon Infotech Research Academy is currently undertaking a project titled "Spatial Analysis of Tuberculosis Prevalence in Nepal from 2019 to 2023." This project aims to investigate the spatial patterns of tuberculosis prevalence in Nepal for the years 2019 and 2023. Additionally, it seeks to identify the associations between tuberculosis prevalence and various factors during these years. By leveraging spatial analysis techniques, the project intends to provide insights into the geographical distribution and influencing factors of tuberculosis, thereby contributing to more effective public health strategies and interventions in Nepal.',
    client: "Axon Infotech Research Academy",
    technologies: ["GIS", "R", "Python", "QGIS"],
    duration: "Ongoing",
    image: "/Images/Project4.jpeg",
    githubRepo: "https://github.com/example/spatial-analysis-tb-nepal",
    status: "Present",
    category: "Public Health",
    tags: ["spatial analysis", "tuberculosis", "public health"],
    date: "June 2023",
    author: "AIRA Team",
  },

  {
    id: 3,
    title:
      "Development of Data-Driven Hybrid Model of ARIMA-CNNAR for Tuberculosis Incidence Time Series Analysis in Nepal",
    image: "/Images/Project3.jpeg",
    description:
      "Axon Infotech Research Academy is currently engaged in developing a data-driven hybrid model combining ARIMA and CNNAR for Tuberculosis (TB) incidence time series analysis in Nepal. The project aims to create an advanced model tailored specifically for analyzing TB incidence, leveraging the strengths of both ARIMA and CNNAR methodologies. By validating the accuracy and reliability of this hybrid model using historical TB incidence data from Nepal, the project seeks to enhance early detection capabilities, optimize resource planning, and improve intervention strategies. This initiative is expected to significantly contribute to combating the tuberculosis epidemic in Nepal through more precise and actionable analysis.",
    client: "Axon Infotech Research Academy",
    technologies: ["ARIMA", "CNNAR", "Python", "TensorFlow", "Pandas"],
    duration: "Ongoing",
    url: "https://example.com/tb-incidence-analysis",
    githubRepo: "https://github.com/example/tb-incidence-analysis",
    status: "Present",
    category: "Healthcare IT",
    tags: ["time series analysis", "TB incidence", "data-driven model"],
    date: "June 2024",
    author: "AIRA Team",
  },

  // Add more projects as needed
];

export const healthWorkBlogs = [
  {
    id: 1,
    title:
      "Leveraging Digital Technology to Achieve Sustainable Development Goals (SDGs)",
    author: "AIRA Team",
    date: "June 1, 2024",
    image: "/Images/Blog 1 image.png", // Replace with actual image path
    content: [
      "In an era defined by rapid technological advancements, the potential of digital technology to drive progress toward achieving the Sustainable Development Goals (SDGs) is immense. The SDGs, established by the United Nations in 2015, consist of 17 goals aimed at addressing global challenges such as poverty, inequality, health, and environmental sustainability by 2030. Digital technology, encompassing everything from mobile devices and cloud computing to artificial intelligence (AI) and the Internet of Things (IoT), plays a crucial role in accelerating progress across these goals.",
      "Enhancing Healthcare Access and Quality (SDG 3: Good Health and Well-being)",
      "Digital technology is revolutionizing healthcare, making it more accessible, efficient, and effective. Telemedicine platforms enable remote consultations, bringing medical expertise to underserved and rural areas. Mobile health (mHealth) applications provide real-time health information and services, empowering individuals to take control of their health. Additionally, AI and machine learning are improving diagnostics, predicting disease outbreaks, and personalizing treatment plans, leading to better health outcomes and reduced healthcare costs.",
      "Promoting Quality Education (SDG 4: Quality Education)",
      "Education is a cornerstone of sustainable development, and digital technology is transforming how education is delivered and accessed. E-learning platforms and massive open online courses (MOOCs) break down geographical barriers, offering quality education to learners worldwide. Interactive digital tools enhance learning experiences, making education more engaging and effective. Furthermore, data analytics in education helps identify learning gaps and tailor educational content to meet the diverse needs of students, ensuring inclusive and equitable education for all.",
      "Fostering Economic Growth and Innovation (SDG 8: Decent Work and Economic Growth)",
      "Digital technology drives economic growth by fostering innovation, increasing productivity, and creating new job opportunities. E-commerce platforms expand market access for businesses, particularly small and medium enterprises (SMEs), enabling them to reach global markets. Digital payment systems and fintech solutions enhance financial inclusion, providing underserved populations with access to financial services. Additionally, the rise of the gig economy and remote work, facilitated by digital platforms, offers flexible employment opportunities, contributing to economic resilience and growth.",
      "Addressing Climate Change and Environmental Sustainability (SDG 13: Climate Action)",
      "Digital technology is instrumental in monitoring and mitigating the impacts of climate change. Remote sensing and IoT devices provide real-time data on environmental conditions, enabling more accurate climate modeling and early warning systems for natural disasters. Smart grids and energy management systems optimize energy consumption, reducing carbon footprints. Furthermore, digital platforms facilitate the sharing economy, promoting sustainable consumption and production patterns. By leveraging digital technology, we can develop innovative solutions to combat climate change and protect our planet for future generations.",
      "Advancing Industry, Innovation, and Infrastructure (SDG 9: Industry, Innovation, and Infrastructure)",
      "Building resilient infrastructure and promoting sustainable industrialization are key to achieving sustainable development. Digital technology enhances infrastructure planning and management through smart city initiatives, which use IoT and data analytics to improve urban living conditions. Blockchain technology ensures transparency and efficiency in supply chains, reducing waste and promoting sustainable practices. Additionally, digital fabrication technologies, such as 3D printing, foster innovation and reduce resource consumption, paving the way for a more sustainable industrial landscape.",
      "Ensuring Inclusive Societies and Reducing Inequalities (SDG 10: Reduced Inequalities)",
      "Digital technology has the potential to bridge social and economic divides, promoting inclusivity and reducing inequalities. Digital identity systems provide marginalized populations with access to essential services, including healthcare, education, and financial services. Social media platforms amplify the voices of underrepresented groups, fostering social cohesion and advocacy for social justice. Moreover, digital literacy initiatives equip individuals with the skills needed to thrive in a digital world, empowering them to participate fully in economic and social life.",
      "Conclusion",
      "The integration of digital technology into sustainable development efforts is not without challenges. Issues such as digital divide, data privacy, and cybersecurity must be addressed to ensure that the benefits of digital technology are accessible to all. However, the potential of digital technology to accelerate progress toward achieving the SDGs is undeniable. By leveraging digital tools and innovations, we can create a more inclusive, equitable, and sustainable world, ensuring a better future for all.",
      "Axon Infotech Research Academy (AIRA) is committed to harnessing the power of digital technology to support the achievement of the SDGs. Through research-based innovations in healthcare technology and data sciences, AIRA aims to contribute to the digital transformation necessary for sustainable development, aligning with the vision of Digital Nepal and the global pursuit of the SDGs.",
    ],
    category: "Technology",
    tags: ["Digital Technology", "SDG"],
    source: "https://example.com/source-url", // Replace with actual source URL
  },
  {
    id: 2,
    title: "The Future of Health is Digital Health",
    author: "AIRA Team",
    date: "June 1, 2024",
    image: "/Images/Blog 2 image.png", // Replace with actual image path
    content: [
      "As we navigate through the 21st century, it’s becoming increasingly clear that the future of health is digital health. The convergence of technology and healthcare is transforming the way we prevent, diagnose, and treat diseases. Digital health encompasses a broad spectrum of technologies including telemedicine, mobile health (mHealth), wearables, artificial intelligence (AI), big data analytics, and more. These advancements are not just enhancing the efficiency of healthcare delivery but also making it more personalized, accessible, and equitable.",
      "The Rise of Telemedicine",
      "Telemedicine has experienced exponential growth, particularly during the COVID-19 pandemic. This technology allows healthcare providers to consult with patients remotely, breaking down geographical barriers and reducing the need for in-person visits. Telemedicine platforms enable real-time consultations, remote monitoring, and follow-ups, making healthcare more accessible, especially for those in rural and underserved areas. The convenience and cost-effectiveness of telemedicine are driving its adoption, and it’s set to become a staple in future healthcare delivery.",
      "Mobile Health (mHealth) Revolution",
      "Mobile health applications are empowering individuals to take charge of their health. From fitness tracking and mental health support to chronic disease management, mHealth apps provide a plethora of services at our fingertips. These applications leverage smartphone technology to deliver personalized health information, reminders for medication adherence, and tools for tracking health metrics. The ubiquity of smartphones ensures that mHealth solutions can reach a wide audience, promoting proactive health management and wellness.",
      "Wearable Technology: Monitoring in Real-Time",
      "Wearable devices, such as smartwatches and fitness trackers, are revolutionizing how we monitor our health. These devices collect real-time data on various health parameters like heart rate, sleep patterns, physical activity, and even blood oxygen levels. By continuously monitoring these metrics, wearables can provide insights into an individual’s health status and alert users to potential health issues before they become critical. Integrating wearable data with healthcare systems allows for more informed clinical decisions and personalized care plans.",
      "Artificial Intelligence and Machine Learning",
      "Artificial intelligence (AI) and machine learning (ML) are at the forefront of the digital health revolution. AI algorithms are being used to analyze vast amounts of health data, leading to more accurate diagnostics, personalized treatment plans, and efficient hospital management. Machine learning models can predict disease outbreaks, identify patterns in patient data, and even assist in surgical procedures. The ability of AI to process and learn from complex datasets is transforming how we understand and address health challenges.",
      "Big Data and Analytics",
      "The explosion of health data from electronic health records (EHRs), wearables, and other digital health tools presents a unique opportunity for big data analytics. By analyzing this data, healthcare providers can gain insights into population health trends, identify risk factors, and develop targeted interventions. Big data analytics also plays a crucial role in precision medicine, where treatments are tailored to individual genetic profiles and lifestyles, enhancing the effectiveness of therapies and improving patient outcomes.",
      "Digital Therapeutics and Remote Monitoring",
      "Digital therapeutics (DTx) are evidence-based interventions delivered via software to prevent, manage, or treat medical conditions. These digital treatments are often prescribed alongside or in place of traditional therapies, providing a new dimension to healthcare. Remote monitoring technologies enable continuous observation of patients’ health outside clinical settings, allowing for early detection of complications and timely interventions. This approach is particularly beneficial for managing chronic conditions such as diabetes, hypertension, and heart disease.",
      "Enhancing Healthcare Access and Equity",
      "Digital health has the potential to bridge the gap in healthcare access and equity. Telemedicine and mHealth can deliver healthcare services to remote and underserved populations, reducing disparities in healthcare availability. Digital tools can also cater to diverse linguistic and cultural needs, making healthcare more inclusive. By lowering the barriers to access, digital health technologies ensure that everyone, regardless of location or socioeconomic status, can receive quality healthcare.",
      "Challenges and the Road Ahead",
      "While the future of health is undoubtedly digital, several challenges need to be addressed. Data privacy and security are paramount, as the increase in digital health tools raises concerns about the protection of sensitive health information. Ensuring interoperability between different digital health systems is crucial for seamless data exchange and integration. Additionally, there is a need for regulatory frameworks to keep pace with technological advancements, ensuring the safety and efficacy of digital health solutions.",
      "Conclusion",
      "The integration of digital technology into healthcare is not just a trend; it’s a transformation that is redefining the future of health. By embracing digital health, we can create a more efficient, personalized, and equitable healthcare system. As innovations continue to emerge, the potential for digital health to improve health outcomes and enhance the quality of life is limitless. Axon Infotech Research Academy (AIRA) is at the forefront of this digital health revolution, committed to harnessing the power of technology to advance healthcare and achieve better health for all.",
    ],
    category: "Digital Health",
    tags: ["Telemedicine", "mHealth", "AI"],
    source: "https://example.com/source-url", // Replace with actual source URL
  },
  {
    id: 4,
    title: "Transforming Patient Care with AI and Big Data in Healthcare",
    author: "AIRA Team",
    date: "June 1, 2024",
    image: "/Images/Blog 3 image.png", // Replace with actual image path
    content: [
      `The healthcare landscape is undergoing a profound transformation with the integration of artificial intelligence (AI) and big data analytics. These digital technologies are not only revolutionizing patient care but also enhancing the efficiency, accuracy, and personalization of healthcare delivery. By leveraging vast amounts of data and advanced algorithms,AI and big data are poised to address some of the most pressing challenges in healthcare today.`,
      "The Power of AI in Diagnostics",
      "One of the most promising applications of AI in healthcare is in diagnostics. AI algorithms can analyze medical images, such as X-rays, MRIs, and CT scans, with remarkable accuracy, often surpassing human radiologists. For instance, AI-powered tools can detect early signs of diseases like cancer, enabling timely intervention and improving patient outcomes. Moreover, AI can integrate data from various sources, including electronic health records (EHRs) and genetic information, to provide a comprehensive diagnostic overview, leading to more accurate and personalized treatment plans.",
      "Predictive Analytics for Proactive Healthcare",
      "Big data analytics enables predictive modeling, which is crucial for proactive healthcare management. By analyzing historical and real-time data, predictive analytics can identify patients at high risk of developing chronic conditions or complications. For example, predictive models can foresee which patients are likely to experience heart attacks or diabetic complications, allowing healthcare providers to intervene early and implement preventive measures. This shift from reactive to proactive healthcare can significantly reduce hospital admissions and improve patient quality of life.",
      "Enhancing Treatment Personalization",
      "AI and big data are pivotal in the era of precision medicine, where treatments are tailored to individual patients based on their unique genetic makeup, lifestyle, and environment. Machine learning algorithms analyze vast datasets to identify patterns and correlations that might not be evident through traditional methods. This enables the development of personalized treatment plans that are more effective and have fewer side effects. For instance, in oncology, AI can help identify the most suitable chemotherapy regimen for a specific patient, maximizing efficacy and minimizing adverse effects.",
      "Streamlining Clinical Workflows",
      "AI and big data are also transforming clinical workflows, making them more efficient and less prone to human error. AI-powered virtual assistants can handle administrative tasks, such as scheduling appointments, managing patient records, and processing billing information. This not only reduces the burden on healthcare staff but also allows them to focus more on patient care. Furthermore, AI-driven tools can assist in clinical decision-making by providing evidence-based recommendations and flagging potential issues, thereby improving the overall quality of care.",
      "Improving Patient Engagement and Adherence",
      "Digital technologies are enhancing patient engagement and adherence to treatment plans. AI-driven chatbots and mobile applications provide patients with real-time information, reminders, and support, encouraging them to follow their treatment regimens and make informed health decisions. These tools can also gather patient feedback and health data, enabling continuous monitoring and timely adjustments to treatment plans. Enhanced patient engagement leads to better health outcomes and increased satisfaction.",
      "Tackling Public Health Challenges",
      "AI and big data are invaluable in addressing public health challenges. During the COVID-19 pandemic, AI models were used to predict the spread of the virus, optimize resource allocation, and develop strategies for containment. Big data analytics provided insights into the effectiveness of interventions and the impact of the pandemic on different populations. These technologies continue to play a critical role in managing public health emergencies, improving response times, and formulating data-driven policies.",
      "Ethical and Privacy Considerations",
      "While the benefits of AI and big data in healthcare are immense, they also raise ethical and privacy concerns. Ensuring the security of sensitive health data is paramount, as breaches can have severe consequences for individuals and healthcare systems. It is essential to develop robust data governance frameworks and adhere to strict privacy regulations to protect patient information. Additionally, transparency in AI decision-making processes and addressing potential biases in algorithms are crucial to building trust and ensuring equitable healthcare delivery.",
      "Conclusion",
      "The integration of AI and big data into healthcare is revolutionizing patient care, making it more accurate, personalized, and efficient. These technologies are transforming diagnostics, enabling proactive healthcare management, and enhancing clinical workflows. As we continue to harness the power of AI and big data, the potential to improve health outcomes and address public health challenges is immense. However, it is essential to navigate the ethical and privacy challenges to ensure that the benefits of these digital technologies are realized while protecting patient rights.",
    ],
    category: "Digital Health",
    tags: ["Patient care", "AI", "Big data"],
    source: "https://example.com/source-url", // Replace with actual source URL
  },
];

// Team Members data in proper format

export const TeamMembers = [
  {
    id: 1,
    Name: "Dr. Roshan Kumar Mahato",
    Post: "Research Advisor",
    Qualification: "Doctor of Public Health (DrPH)",
    Affiliated:
      "Faculty of Public Health, Khon Kaen University, Khon Kaen, Thailand",
    Brief:
      "Asst. Prof. Dr. Roshan Kumar Mahato holds a Doctor of Public Health (2019) and a Master of Public Health in International Health (2015) from Khon Kaen University, Thailand. Dr. Mahato serves as an Assistant Professor at Khon Kaen University and has held administrative roles at Dhulikhel Hospital. His expertise includes geoinformatics, epidemiology, infectious diseases, public health, biostatistics, and big data analysis.",
    Image: "/Research/1. Dr Roshan Kumar Mahato.jpg",
  },

  {
    id: 3,
    Name: " Mr. Sailendra Chaudhary",
    Post: "Consultant",
    Qualification: "Master in Pharmacy",
    "Affiliated Organization": "HoD (Pharmacy Department in MBAHS)",
    Brief:
      "Mr. Sailendra Chaudhary earned his Master’s degree in Advanced Spectroscopy through a joint program from the University of Lille, France, and the University of Leipzig, Germany. He serves as the Head of the Pharmacy Department at Madan Bhandari Academy of Health Sciences in Nepal.",
    Image: "/Research/3. Sailendra Chaudhary.jpg",
  },
  {
    id: 4,
    Name: " Mr. Nirmal Gautam",
    Post: "Consultant",
    Qualification: "PhD candidate in Health Economics",
    "Affiliated Organization": "Queensland University in Australia",
    Brief:
      "Nirmal Gautam is pursuing a PhD in Health Economics at Queensland University in Australia. He holds an M.Sc. in Research Methodology from Prince of Songkla University, Thailand, and a BPH from Purbanchal University, Nepal.",
    Image: "/Research/4. Nirmal Gautam.jpg",
  },
  {
    id: 5,
    Name: " Mr. Yogesh Chaudhary",
    Post: "Consultant",
    Qualification: "M. Pharm. (Quality Assurance)",
    "Affiliated Organization": "Madan Bhandari Academy of Health Sciences",
    Brief:
      "Mr. Chaudhary graduated from Pokhara University in 2008 with Bachelor in Pharmaceutical Sciences degree and started professional career as an industrial pharmacist. Since then he has been working in various capacities like Production Pharmacist, FR&D Manager, QA Manager in many renowned pharmaceutical companies before joining MBAHS as a Lecturer.",
    Image: "/Research/5. Yogesh Chaudhary.jpg",
  },
  {
    id: 6,
    Name: "Mr. Bipindra Pandey",
    Post: "Consultant",
    Qualification: "Master of Pharmaceutical Sciences",
    "Affiliated Organization": "Madan Bhandari Academy of Health Sciences",
    Brief:
      "Mr. Bipindra Pandey holds a Master of Pharmaceutical Sciences from Pokhara University, Nepal. He has received honors during his studies and is associated with Madan Bhandari Academy of Health Sciences.",
    Image: "/Research/6. Bipindra Pandey.jpg",
  },
  {
    id: 7,
    Name: "Mr. Krishna Bdr. G.C.",
    Post: "Consultant",
    Qualification: "PhD candidate in Research Methodology and Data Analysis",
    "Affiliated Organization": "Prince of Songkla University, Thailand",
    Brief:
      "Mr. Krishna Bdr. G.C. is a PhD candidate at Prince of Songkla University, Thailand, specializing in Research Methodology and Data Analysis. He holds an M.Sc. in Statistics from Tribhuvan University, Nepal.",
    Image: "/Research/7 Krishna Bahadur GC.jpg",
  },
  {
    id: 8,
    Name: "Mr. Lokjan Singh",
    Post: "Consultant",
    Qualification:
      "Master in Medical Microbiology (Assistant Professor / KAHS)",
    "Affiliated Organization": "Karnali Academy of Health Sciences",
    Brief:
      "Mr. Lokjan Singh is an Assistant Professor in Clinical Microbiology at Karnali Academy of Health Sciences, Nepal. He holds a Master’s degree in Medical Microbiology and has contributed significantly to infectious disease research and pandemic response.",
    Image: "Research/8 Lokjan Singh.jpg",
  },
  {
    id: 9,
    Name: "Dr. Seejan Rawal",
    Post: "Consultant",
    Qualification: "MD in Internal Medicine",
    "Affiliated Organization": "",
    Brief:
      "Dr. Seejan Rawal is a Doctor of Medicine specializing in Internal Medicine. He completed his medical education in Bangladesh and Nepal, demonstrating a commitment to advancing healthcare in internal medicine.",
    Image: "/Research/9. Dr Seejan Rawal.jpg",
  },
  {
    id: 11,
    Name: "Dr. Bhisma Pokharel",
    Post: "Consultant",
    Qualification: "MD in Radiodiagnosis",
    "Affiliated Organization": "Kalikot District Hospital",
    Brief:
      "Dr. Bhisma Pokharel is a Doctor of Medicine specializing in Radiodiagnosis. He is affiliated with Kalikot District Hospital in Nepal.",
    Image: "/Research/11 Dr Bhishma Pokharel.jpg",
  },
  {
    id: 2,
    Name: "Mr. Deepak Bahadur Singh",
    Post: "Researcher",
    Qualification: "MPH (Epidemiology)",
    "Affiliated Organization": "K S Hegde Medical academy, Mangalore, India",
    Brief:
      "Mr. Deepak Bahadur Singh is a researcher specializing in Epidemiology, holding a Master of Public Health degree. He is associated with K S Hegde Medical Academy in Mangalore, India.",
    Image: "/Research/2. Deepak Bahadur Singh.jpg",
  },
  {
    id: 2,
    Name: "Mr. Bibek Giri",
    Post: "Consultant",
    Qualification: "PhD candiadate at Hoseo University, South Korea",
    "Affiliated Organization": "K S Hegde Medical academy, Mangalore, India",
    Brief:
      "Bibek Giri is pursuing a Ph.D. at Hoseo University in South Korea. He holds a Master of Science in Global Health and Development from Hanyang University, South Korea and B.Sc. MLT from Rajiv Gandhi University of Health Sciences, Bangalore, India. He has contributed to various research projects and served as a peer reviewer in many prestigious journals. His research areas of interest include infectious diseases, Migrant Health, Mental Health, and can contribute to various public health issues.",
    Image: "/Research/12 Mr Bibek Giri.jpg",
  },
  {
    id: 2,
    Name: "Mr. Shankar Thapa",
    Post: "Consultant",
    Qualification: "Master in Pharmacy (Medicinal Chemistry)",
    "Affiliated Organization": "K S Hegde Medical academy, Mangalore, India",

    //
    Brief:
      "Shankar Thapa is currently serving as a Lecturer of Medicinal Chemistry at the Department of Pharmacy, Madan Bhandari Academy of Health Sciences, Hetauda. Prior to this role, he held a similar position at Universal College of Medical Sciences and Teaching Hospitals in Bhairahawa. Since 2018, Additionally, he is a visiting faculty member at Narugnd College of Pharmacy in India. His academic credentials include a B.Pharmacy degree from Tribhuvan University and a Master's in Pharmacy (Medicinal Chemistry) from Rajiv Gandhi University of Health Sciences in India.",
    Image: "/Research/13. Mr Shankar Thapa.JPG",
  },
  {
    id: 4,
    Name: "Mrs. Yashoda Dangi",
    Post: "Former Research Associate",
     Qualification: "Bachelor of Public Health (BPH)",
    Image: "/AdminTeam/Yashoda.jpeg",
    Brief: "Yashoda Dangi is an experienced public health professional with a strong interest in research and innovation. She has worked across diverse health programs to improve population health outcomes.",
  },
];

export const fallbackImage =
  "https://static.vecteezy.com/system/resources/previews/005/337/799/original/icon-image-not-found-free-vector.jpg";

// Sample data for CEO
export const CEO = [
  {
    id: 2,
    name: "Mr. Sudarsan Dahal",
    post: "Operation Head",
    introduction:
      "Sudarsan Dahal is an accomplished professional with over 12 years of extensive experience in the Development sector in Nepal. He specializes in project implementation, management, and administration, with expertise in public-private partnerships, health system strengthening, and capacity building.",
    Image: "/AdminTeam/Advisor Sudarshan Dahal.jpg", // Placeholder URL
    Qualification: "MA Sociology, MA Rural Development",
  },

];
// Sample data for admin members (Advisory Team)
export const AdminMembers = [
  {
    id: 1,
    name: "Mr. D.B. Singh",
    post: "Advisor ",
    introduction:
      "Mr. Dip Bahadur Singh completed his Diploma in General Medicine from All Nepal College of Medical Sciences in 2012. He has a Bachelor of Public Health from Asian College of Advanced Studies. He has completed Master's in Health Informatics from Kathmandu University.",
    photoUrl: "/AdminTeam/Advisor DB Singh.jpg", // Placeholder URL
    Qualification: "Health Informatics / Digital Health",
  },
  {
    id: 3,
    name: "Mr. Subash Dawadi",
    post: "Advisor",
    introduction:
      "Mr. Subash Dawadi has completed a Master's in Health Informatics at Kathmandu University. He has a background in public health and health informatics, with experience in roles such as Health Assistant and District Program Officer.",
    photoUrl: "/AdminTeam/Advisor Subash Dawadi.jpeg", // Placeholder URL
    Qualification: "Master in Health Informatics",
  },
  {
    id: 3,
    name: "Mr. Bikash Regmi",
    post: "Legal Advisor",
    introduction:
      "Bikash Regmi is a Legal Adviser of Axon Infotech Research Academy and has been with as since established.  He is one of the well known youth lawyers of Nepal who has extensive experience in the matter of corporate law, dispute resolution and Cyber Law.  Bikash completed his Bachelor Degree from the Tribhuvan University. He is Advocate licensed by Nepal Bar Council. ",
    photoUrl: "", // Placeholder URL
    Qualification: "Advocate / BALLB (TU)",
  },
   
];

export const ABCD = [
  {
    "Health Professions": [
      "MMWR Recommendations and Reports",
      "Morbidity and Mortality Weekly Report",
      "MMWR Surveillance Summaries",
      "Lancet Digital Health, The",
      "npj Digital Medicine",
      "Sports Medicine",
      "Journal of Sport and Health Science",
      "International Journal of Behavioral Nutrition and Physical Activity",
      "Journal of Cardiovascular Magnetic Resonance",
      "Journal of Physiotherapy",
      "Journal of Bone and Joint Surgery",
      "Human Brain Mapping",
      "Eye and Vision",
      "Biology of Sport",
      "Sports Medicine - Open",
      "Health systems and reform",
      "Echo Research and Practice",
      "BMJ Open Sport and Exercise Medicine",
      "Neurophotonics",
      "Cancer Imaging",
      "Journal of Educational Evaluation for Health Professions",
      "Journal of Athletic Training",
      "Journal of Strength and Conditioning Research",
      "Clinical eHealth",
      "BMJ Health and Care Informatics",
      "American Journal of Pharmaceutical Education",
      "Diagnostic and interventional imaging",
      "Learning Health Systems",
      "Health Equity",
      "Journal of Pharmaceutical Analysis",
      "Innovation in Aging",
      "International Journal of Health Policy and Management",
      "Animal Models and Experimental Medicine",
      "Brazilian Journal of Physical Therapy",
      "JMIR Serious Games",
      "Journal of Sports Science and Medicine",
      "Research Involvement and Engagement",
      "JMIR Medical Informatics",
      "Journal of the International Society of Sports Nutrition",
      "Ultrasound Journal",
      "JMIR Infodemiology",
      "Journal of Patient-Reported Outcomes",
      "Foods",
      "Arthroscopy, Sports Medicine, and Rehabilitation",
      "Complementary Therapies in Medicine",
      "Trends in hearing",
      "International Journal of Hyperthermia",
      "Journal of Human Kinetics",
      "Journal of Rehabilitation Medicine",
      "Sports Medicine and Health Science",
    ],

    Mathematics: [
      "Molecular Systems Biology",
      "PRX Quantum",
      "Genomics, Proteomics and Bioinformatics",
      "Forum of Mathematics, Pi",
      "Journal of the European Mathematical Society",
      "Journal of Machine Learning Research",
      "Journal of Statistical Software",
      "Annales de l'Institut Henri Poincare (C) Analyse Non Lineaire",
      "Bioinformatics",
      "NAR Genomics and Bioinformatics",
      "npj Computational Materials",
      "Virtual and Physical Prototyping",
      "NPG Asia Materials",
      "IEEE Robotics and Automation Letters",
      "Geoscientific Model Development",
      "Advanced Nonlinear Studies",
      "Scientific data",
      "Advances in Nonlinear Analysis",
      "Advances in Combinatorics",
      "International Journal of Systems Science",
      "Quantitative Science Studies",
      "Statistics Surveys",
      "PLoS Computational Biology",
      "mSystems",
      "Forum of Mathematics, Sigma",
      "Network Neuroscience",
      "Journal de l'Ecole Polytechnique - Mathematiques",
      "EMS Surveys in Mathematical Sciences",
      "Algebraic Geometry",
      "Revista Matematica Iberoamericana",
      "Commentarii Mathematici Helvetici",
      "Electronic Journal of Probability",
      "Bulletin of the American Mathematical Society",
      "Annales de l'Institut Henri Poincare (D) Combinatorics, Physics and their Interactions",
      "Complex and Intelligent Systems",
      "SMAI Journal of Computational Mathematics",
      "Theory of Computing",
      "Electronic Journal of Statistics",
      "npj Systems Biology and Applications",
      "Systems Science and Control Engineering",
      "ESAIM: Mathematical Modelling and Numerical Analysis",
      "Transactions of the American Mathematical Society Series B",
      "Mathematics of Operations Research",
      "Documenta Mathematica",
      "Quantum Topology",
      "IACR Transactions on Symmetric Cryptology",
      "Biology Direct",
      "Engineering Applications of Computational Fluid Mechanics",
      "Epijournal de Geometrie Algebrique",
      "Advances in Statistical Climatology, Meteorology and Oceanography",
    ],
    Medicine: [
      "World Psychiatry",
      "MMWR Recommendations and Reports",
      "Morbidity and Mortality Weekly Report",
      "MMWR Surveillance Summaries",
      "Lancet Public Health, The",
      "Molecular Cancer",
      "Journal of Hematology and Oncology",
      "Lancet Digital Health, The",
      "Intensive Care Medicine",
      "Lancet Global Health, The",
      "Annals of the Rheumatic Diseases",
      "JAMA Pediatrics",
      "Lancet Microbe, The",
      "Molecular Systems Biology",
      "Molecular Neurodegeneration",
      "Lancet Planetary Health, The",
      "Genome Medicine",
      "Lancet Regional Health - Europe, The",
      "Cancer Communications",
      "Journal of Clinical Investigation",
      "GigaScience",
      "Protein and Cell",
      "Lancet Healthy Longevity, The",
      "npj Digital Medicine",
      "Journal of Extracellular Vesicles",
      "PLoS Medicine",
      "Blood Cancer Journal",
      "eLife",
      "Advanced Science",
      "Microbiome",
      "Journal for ImmunoTherapy of Cancer",
      "Lancet Rheumatology, The",
      "Experimental and Molecular Medicine",
      "Liver Cancer",
      "eClinicalMedicine",
      "Sports Medicine",
      "JAMA network open",
      "JHEP Reports",
      "Bone Research",
      "Genomics, Proteomics and Bioinformatics",
      "Translational Neurodegeneration",
      "JAMA Dermatology",
      "eBioMedicine",
      "Clinical and Molecular Hepatology",
      "Gut Microbes",
      "Dialogues in Clinical Neuroscience",
      "Biomarker Research",
      "Critical Care",
      "Engineered Regeneration",
      "JCI insight",
    ],
    "Biochemistry, Genetics and Molecular Biology": [
      "Cell Genomics",
      "Signal Transduction and Targeted Therapy",
      "Molecular Cancer",
      "Annual Review of Plant Biology",
      "Journal of Hematology and Oncology",
      "Genome Biology",
      "Nucleic Acids Research",
      "Annals of the Rheumatic Diseases",
      "Journal of the American Chemical Society",
      "Molecular Systems Biology",
      "Molecular Neurodegeneration",
      "Genome Medicine",
      "Cancer Communications",
      "Nature Communications",
      "Protein and Cell",
      "Cell Reports",
      "Cell Reports Medicine",
      "Journal of Extracellular Vesicles",
      "Cell Discovery",
      "PLoS Medicine",
      "Molecular Biology and Evolution",
      "Aggregate",
      "EMBO Molecular Medicine",
      "eLife",
      "Advanced Science",
      "PLoS Biology",
      "Journal for ImmunoTherapy of Cancer",
      "Experimental and Molecular Medicine",
      "Bioactive Materials",
      "Bone Research",
      "Genomics, Proteomics and Bioinformatics",
      "Evolution Letters",
      "iMeta",
      "eBioMedicine",
      "Ultrafast Science",
      "Clinical and Molecular Hepatology",
      "Plant Communications",
      "Molecular Metabolism",
      "Biomarker Research",
      "Biomaterials",
      "Redox Biology",
      "Plant Biotechnology Journal",
      "Journal of the National Cancer Center",
      "Aging Cell",
      "Journal of Bioresources and Bioproducts",
      "npj Precision Oncology",
      "Journal of Experimental and Clinical Cancer Research",
      "Journal of Biomedical Science",
      "Breast Cancer Research",
      "Bioinformatics",
    ],
    "Computer Science": [
      "AI Open",
      "Nature Machine Intelligence",
      "Molecular Systems Biology",
      "PRX Quantum",
      "GigaScience",
      "Computational Visual Media",
      "npj Digital Medicine",
      "Transactions of the Association for Computational Linguistics",
      "Computers and Education: Artificial Intelligence",
      "npj Quantum Information",
      "Journal of Machine Learning Research",
      "IEEE Open Journal of the Communications Society",
      "Journal of Statistical Software",
      "Intelligent and Converged Networks",
      "International Journal of Educational Technology in Higher Education",
      "Bioinformatics",
      "Journal of Metaverse",
      "NAR Genomics and Bioinformatics",
      "Big Data and Society",
      "npj Computational Materials",
      "Satellite Navigation",
      "Virtual and Physical Prototyping",
      "Energy and AI",
      "IEEE Open Journal of the Computer Society",
      "Social Media and Society",
      "International Journal of Information Management Data Insights",
      "IEEE Robotics and Automation Letters",
      "Cell Reports Methods",
      "Journal of Big Data",
      "Journal of Memory and Language",
      "Digital Communications and Networks",
      "Scientific data",
      "Big Data Mining and Analytics",
      "IACR Transactions on Cryptographic Hardware and Embedded Systems",
      "APL Photonics",
      "International Journal of Systems Science",
      "Data Science and Engineering",
      "IEEE Transactions on Green Communications and Networking",
      "International Journal of Cognitive Computing in Engineering",
      "Human Behavior and Emerging Technologies",
      "Journal of Cheminformatics",
      "PLoS Computational Biology",
      "Engineering",
      "mSystems",
      "Sustainable Operations and Computers",
      "Journal of Artificial Intelligence Research",
      "Network Neuroscience",
      "Smart Learning Environments",
      "Railway Engineering Science",
      "Database : the journal of biological databases and curation",
    ],
    "Decision Sciences": [
      "Lancet Digital Health, The",
      "Management Science",
      "Journal of Statistical Software",
      "Communications in Transportation Research",
      "Big Data and Society",
      "Research Policy: X",
      "International Journal of Information Management Data Insights",
      "Journal of Big Data",
      "Scientific data",
      "International Journal of Cognitive Computing in Engineering",
      "Statistics Surveys",
      "Decision Making: Applications in Management and Engineering",
      "Ecological Indicators",
      "Sustainable Operations and Computers",
      "Journal of Responsible Innovation",
      "Patterns",
      "Transportation Research Interdisciplinary Perspectives",
      "Data Science and Management",
      "Electronic Journal of Probability",
      "Electronic Journal of Statistics",
      "Egyptian Informatics Journal",
      "Mathematics of Operations Research",
      "Journal of Management Science and Engineering",
      "Comparative Migration Studies",
      "Journal of Applied Structural Equation Modeling",
      "Stochastic Systems",
      "Judgment and Decision Making",
      "EURO Journal on Computational Optimization",
      "Sustainable Futures",
      "Journal of Safety Science and Resilience",
      "Journal of Choice Modelling",
      "Methods, Data, Analyses",
      "International Journal of Innovation Studies",
      "Journal of Causal Inference",
      "International Journal of Population Data Science",
      "Operations Research Perspectives",
      "International Journal of Engineering Business Management",
      "Operational Research in Engineering Sciences: Theory and Applications",
      "Asian Journal of Shipping and Logistics",
      "R Journal",
      "Logistics",
      "Social Sciences and Humanities Open",
      "Decision Analytics Journal",
      "Journal of Statistical Distributions and Applications",
      "Statistical Papers",
      "Journal of Statistics and Data Science Education",
      "Electronic Communications in Probability",
      "International Journal of Information Systems and Project Management",
      "Australasian Journal of Information Systems",
      "Interfaces",
    ],
    Multidisciplinary: [
      "The Innovation",
      "Science advances",
      "Proceedings of the National Academy of Sciences of the United States of America",
      "National Science Review",
      "Research",
      "Journal of Advanced Research",
      "Tsinghua Science and Technology",
      "iScience",
      "Progress in Natural Science: Materials International",
      "Global Challenges",
      "Scientific Reports",
      "Proceedings of the Japan Academy Series B: Physical and Biological Sciences",
      "Fundamental Research",
      "Facets",
      "PLoS ONE",
      "Royal Society Open Science",
      "Emerging Science Journal",
      "Epidemiologia e servicos de saude : revista do Sistema Unico de Saude do Brasil",
      "Citizen Science: Theory and Practice",
      "Science and Technology Studies",
      "Health Data Science",
      "Heliyon",
      "Journal of King Saud University - Science",
      "Scientific African",
      "Applied Network Science",
      "Complexity",
      "Science Progress",
      "Sci",
      "International Journal of Technology",
      "Tapuya: Latin American Science, Technology and Society",
      "Latin American Research Review",
      "Acta Polytechnica Hungarica",
      "European Journal of STEM Education",
      "Sadhana - Academy Proceedings in Engineering Sciences",
      "AAS Open Research",
      "Anais da Academia Brasileira de Ciencias",
      "Interaction Design and Architecture(s)",
      "Historia Agraria",
      "Open Research Europe",
      "Karbala International Journal of Modern Science",
      "Gateways",
      "ScienceAsia",
      "Brazilian Archives of Biology and Technology",
      "Current Science",
      "Kuwait Journal of Science",
      "Shanghai Jiaotong Daxue Xuebao/Journal of Shanghai Jiaotong University",
      "Journal of Scientific and Industrial Research",
      "Data in Brief",
      "Experimental Results",
      "European Journal of Science and Theology",
    ],
    Nursing: [
      "International Journal of Behavioral Nutrition and Physical Activity",
      "Public Health Reviews",
      "Clinical and Translational Immunology",
      "Nutrients",
      "Nutrition Journal",
      "Echo Research and Practice",
      "JMIR Aging",
      "Maternal and Child Nutrition",
      "BMJ Nutrition, Prevention and Health",
      "International Journal of Health Policy and Management",
      "Journal of Eating Disorders",
      "Journal of Healthcare Leadership",
      "Global Heart",
      "Nutrition and Metabolism",
      "European Geriatric Medicine",
      "NFS Journal",
      "BMC Medical Ethics",
      "International Journal of Nursing Sciences",
      "Journal of the International Society of Sports Nutrition",
      "Food Hydrocolloids for Health",
      "Journal of Functional Foods",
      "JMIR Nursing",
      "BMC Nursing",
      "Journal of Primary Care and Community Health",
      "Journal of Future Foods",
      "Clinical and Experimental Pediatrics",
      "Public Health Nutrition",
      "Canadian Geriatrics Journal",
      "Journal of the Egyptian Public Health Association, The",
      "Complementary Therapies in Medicine",
      "Food and Nutrition Research",
      "Current Developments in Nutrition",
      "Frontiers in Nutrition",
      "Obesity Science and Practice",
      "Food Production, Processing and Nutrition",
      "International Journal of Nursing Studies Advances",
      "Nursing Open",
      "International Journal of Qualitative Studies on Health and Well-being",
      "Resuscitation Plus",
      "International Journal of Women's Health",
      "Journal of Exercise Science and Fitness",
      "Asian Nursing Research",
      "Journal of Multidisciplinary Healthcare",
      "Archives of Academic Emergency Medicine",
      "Technical Innovations and Patient Support in Radiation Oncology",
      "International Journal of Community Based Nursing and Midwifery",
      "Journal of Nutritional Science",
      "Nursing Reports",
      "Primary Health Care Research and Development",
      "Healthcare (Switzerland)",
    ],
    "Immunology and Microbiology": [
      "Annals of the Rheumatic Diseases",
      "Lancet Microbe, The",
      "Molecular Systems Biology",
      "eLife",
      "PLoS Biology",
      "Microbiome",
      "Journal for ImmunoTherapy of Cancer",
      "Lancet Rheumatology, The",
      "iMeta",
      "Gut Microbes",
      "Eurosurveillance",
      "Journal of Neuroinflammation",
      "Cell Death and Disease",
      "OncoImmunology",
      "Emerging Microbes and Infections",
      "PLoS Pathogens",
      "Open Biology",
      "ImmunoTargets and Therapy",
      "npj Vaccines",
      "International Journal of Biological Sciences",
      "mBio",
      "Immunity and Ageing",
      "Virus Evolution",
      "npj Biofilms and Microbiomes",
      "Frontiers in Immunology",
      "Journal of Nanobiotechnology",
      "RMD Open",
      "Inflammation and Regeneration",
      "Environmental Microbiome",
      "Clinical and Translational Immunology",
      "mAbs",
      "Cell Death Discovery",
      "mSystems",
      "Arthritis Research and Therapy",
      "Immune Network",
      "Pathogens and Immunity",
      "Expert Review of Vaccines",
      "DMM Disease Models and Mechanisms",
      "Antibody Therapeutics",
      "Microbial genomics",
      "International Journal of Neonatal Screening",
      "Virulence",
      "Clinical and Translational Allergy",
      "MicroLife",
      "Frontiers in Cellular and Infection Microbiology",
      "Lupus Science and Medicine",
      "Journal of Translational Autoimmunity",
      "mSphere",
      "International Journal for Parasitology: Drugs and Drug Resistance",
      "World Allergy Organization Journal",
    ],
    Neuroscience: [
      "eLife",
      "PLoS Biology",
      "Translational Neurodegeneration",
      "Dialogues in Clinical Neuroscience",
      "Journal of Neuroinflammation",
      "Neurology: Neuroimmunology and NeuroInflammation",
      "Alzheimer's Research and Therapy",
      "Acta neuropathologica communications",
      "Cell Death and Disease",
      "Brain Stimulation",
      "NeuroImage",
      "Translational Psychiatry",
      "Open Biology",
      "npj Parkinson's Disease",
      "Neurobiology of Disease",
      "Fluids and Barriers of the CNS",
      "Molecular Autism",
      "Brain Pathology",
      "Developmental Cognitive Neuroscience",
      "Brain Communications",
      "Neurobiology of Stress",
      "Annals of Clinical and Translational Neurology",
      "Cell Death Discovery",
      "PLoS Computational Biology",
      "Social Cognitive and Affective Neuroscience",
      "Human Brain Mapping",
      "Neurobiology of Language",
      "Chronic Stress",
      "Neural Development",
      "Schizophrenia",
      "Network Neuroscience",
      "Frontiers in Neural Circuits",
      "Implementation Research and Practice",
      "Frontiers in Synaptic Neuroscience",
      "Frontiers in Cellular Neuroscience",
      "General Psychiatry",
      "Therapeutic Advances in Neurological Disorders",
      "NeuroImage: Clinical",
      "Investigative Ophthalmology and Visual Science",
      "Journal of Neurodevelopmental Disorders",
      "Journal of Cognitive Neuroscience",
      "Borderline Personality Disorder and Emotion Dysregulation",
      "Computers in Human Behavior Reports",
      "DMM Disease Models and Mechanisms",
      "Journal of Psychiatry and Neuroscience",
      "IEEE Transactions on Neural Systems and Rehabilitation Engineering",
      "Molecular Brain",
      "International Journal of Bipolar Disorders",
      "Journal of Parkinson's Disease",
    ],
    "Economics, Econometrics and Finance": [
      "Quantitative Economics",
      "Theoretical Economics",
      "Journal of Innovation and Knowledge",
      "Sustainable Technology and Entrepreneurship",
      "Resources, Conservation and Recycling Advances",
      "European Research on Management and Business Economics",
      "Carbon Neutrality",
      "Schmalenbach Journal of Business Research",
      "Financial Innovation",
      "Journal of Institutional Economics",
      "Eurasian Business Review",
      "Judgment and Decision Making",
      "Borsa Istanbul Review",
      "Swiss Journal of Economics and Statistics",
      "International Journal of Wellbeing",
      "BRQ Business Research Quarterly",
      "Oeconomia Copernicana",
      "She Ji",
      "Intereconomics",
      "Virtual Economics",
      "Journal of Competitiveness",
      "Journal of Open Innovation: Technology, Market, and Complexity",
      "Journal of Innovation and Entrepreneurship",
      "Humanities and Social Sciences Communications",
      "International Journal of Agricultural Sustainability",
      "Technological and Economic Development of Economy",
      "Palgrave Communications",
      "Economic Research-Ekonomska Istrazivanja",
      "China Journal of Accounting Research",
      "Research in Globalization",
      "Journal of Economic Structures",
      "Agricultural and Food Economics",
      "Cleaner and Responsible Consumption",
      "ClinicoEconomics and Outcomes Research",
      "SERIEs",
      "European Journal of Management and Business Economics",
      "European Journal of Futures Research",
      "PSU Research Review",
      "Trees, Forests and People",
      "Journal of Current Chinese Affairs",
      "Equilibrium. Quarterly Journal of Economics and Economic Policy",
      "IZA Journal of Development and Migration",
      "Econometrics",
      "China Economic Quarterly International",
      "Nonprofit Policy Forum",
      "Journal of Agricultural & Applied Economics",
      "Journal of Advanced Transportation",
      "Journal of Asian Business and Economic Studies",

      "Journal of Business Economics and Management",
    ],
    "Social Sciences": [
      "Nature Sustainability",
      "Lancet Planetary Health, The",
      "Lancet Healthy Longevity, The",
      "Transactions of the Association for Computational Linguistics",
      "Harvard Kennedy School Misinformation Review",
      "Computers and Education: Artificial Intelligence",
      "Communications in Transportation Research",
      "International Journal of Educational Technology in Higher Education",
      "Journal of Metaverse",
      "Big Data and Society",
      "Journal of Computer-Mediated Communication",
      "Policy and Society",
      "Social Media and Society",
      "International Journal of Information Management Data Insights",
      "Weather and Climate Extremes",
      "International Journal of STEM Education",
      "Biology of Sex Differences",
      "Journal of Memory and Language",
      "Digital Communications and Networks",
      "Multimodal Transportation",
      "Scientific data",
      "European Journal of Psychology Applied to Legal Context",
      "International Journal of Qualitative Methods, The",
      "Quantitative Science Studies",
      "Geography and Sustainability",
      "Human Behavior and Emerging Technologies",
      "Human-Machine Communication",
      "Journal of Cheminformatics",
      "Earth System Governance",
      "Global Transitions",
      "SSM - Population Health",
      "AERA Open",
      "Human Resources for Health",
      "Smart Learning Environments",
      "Railway Engineering Science",
      "Educational Technology and Society",
      "Journal of Democracy",
      "Journal of Migration and Health",
      "Global Health Research and Policy",
      "Journal of Intelligent and Connected Vehicles",
      "Survey Research Methods",
      "Journal of Learning Analytics",
      "Health Reports",
      "Transportation Research Interdisciplinary Perspectives",
      "Sustainability: Science, Practice, and Policy",
      "Energy and Built Environment",
    ],
    "Metadata services": [
      "AGRIS: Agricultural database",
      "Arachne",
      "AMiner",
      "Arts & Humanities Citation Index",
      "Astrophysics Data System",
      "ATLA Religion Database",
      "BASE: Bielefeld Academic Search Engine",
      "Book Review Index Online",
      "Books in Print",
      "CAB Abstracts",
      "CINAHL: Cumulative Index to Nursing and Allied Health",
      "CiNii",
      "CNKI",
      "CORE",
      "Crossref",
      "DeepDyve",
      "Dimensions",
      "Directory of Open Access Journals (DOAJ)",
      "DBLP",
      "EconBiz",
      "EconLit",
      "EMBASE",
      "FSTA – Food Science and Technology Abstracts",
      "GeoRef",
      "Google Scholar",
      "Informit",
      "Inspec",
      "International Nuclear Information System (INIS)",
      "International Philosophical Bibliography",
      "J-Gate",
      "The Lens",
      "MathSciNet",
      "MEDLINE",
      "MyScienceWork",
      "National Diet Library Collection",
      "OAIster",
      "OpenAIRE Graph",
      "OpenAlex",
      "PsycINFO",
      "PubMed",
      "RSWBplus",
      "Russian Science Citation Index",
      "ScienceOpen",
      "Scopus",
      "Web of Science",
    ],
  },
];
